#!/usr/bin/env bash

# scripy to start a MySQL server with a mapped local directory for data

docker rm -f mariadb-server >/dev/null 2>/dev/null
docker run -d \
        --name mariadb-server \
        -e MYSQL_ROOT_PASSWORD=rootpass \
        -e MYSQL_USER=moodle_user \
        -e MYSQL_PASSWORD=moodle \
        -e MYSQL_ROOT_HOST=172.17.0.1 \
        -p 3307:3306 \
	-v ~/workbench/mariadb/data:/var/lib/mysql \
 mariadb:10.11

echo "=> install mysql-client"
docker exec -it mariadb-server apt update >/dev/null 2>/dev/null
docker exec -it mariadb-server apt install -y mysql-client >/dev/null 2>/dev/null
echo "=> grant full privileges to moodle_user"
docker exec -it mariadb-server mysql -uroot -prootpass -e "GRANT ALL PRIVILEGES ON *.* TO 'moodle_user'@'%' IDENTIFIED BY 'moodle';" >/dev/null 2>/dev/null
docker exec -it mariadb-server mysql -uroot -prootpass -e "FLUSH PRIVILEGES;" >/dev/null 2>/dev/null
echo "-------------------"
ipaddr=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" mariadb-server)
echo "mariadb-server running on $ipaddr"

